[package]
name = "animegan_rs_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
ort = "=2.0.0-rc.9"
image = "0.24"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
ndarray = "0.16.1"
jni = "0.20.0"


[lib]
name = "animegandemo"
path = "src/lib.rs"
crate-type = ["dylib"]